Add stratisd.spec for mock build
stratis-storage/ci pull request #131
Opened 2021-01-13 20:59 UTC by bgurney-rh

Supersedes: #128 
Related: stratis-storage/project#249

2021-01-13 22:46 UTC, mulkieran requested changes
This looks reasonable to me. Can you change the directory name from mock to unified?

2021-01-13 22:52 UTC, bgurney-rh commented
Done; the new directory name is now "unified".

2021-01-13 23:12 UTC, mulkieran approved these changes

2021-01-14 14:43 UTC, jbaublitz approved these changes

2021-01-14 14:47 UTC, drckeefe approved these changes

2021-01-14 14:59 UTC, merged