Add _set_up_subcommand function
stratis-storage/ci pull request #418
Opened 2023-06-12 21:30 UTC by bgurney-rh

Related: #405

2023-06-13 16:22 UTC, mulkieran requested changes

2023-06-13 20:31 UTC, bgurney-rh commented on release_management/create_release.py
> +    :param str help_string: the help string
Resolved.

2023-06-14 16:00 UTC, mulkieran commented
> This should cover all of the Rust libraries that don't have any extra arguments (except for stratisd_proc_macros; should I convert that?)

Yes. Please. Do stratisd_proc_macros as well.

2023-06-15 17:22 UTC, bgurney-rh commented
OK; I updated that yesterday, but forgot to push.

2023-06-15 17:25 UTC, bgurney-rh commented
Squashed into a single commit.

2023-06-15 18:59 UTC, mulkieran requested changes
The refactoring looks good.

I have two further requests for this PR:

1. Change the name "libblkid" to "libblkid-rs".  "libblkid-rs" is both the repo name and the package name, so it is a better choice. For exactly the same reasons, "libcryptsetup" should be "libcryptsetup-rs". 

2. Remove ``` # pylint: disable=too-many-locals``` from the ```_get_parser``` method. With your refactoring, it's no longer the case.

You can leave both these requested changes in separate commits.

2023-06-16 16:17 UTC, mulkieran approved these changes

2023-06-16 16:47 UTC, merged